### PR TITLE
Feature/dimensions

### PR DESCRIPTION
**Pull request by timelyportfolio**
This pull bumps version to `0.3.0`.  

### New Functionality

-addition of `dimensions` customization introduced in https://github.com/syntagmatic/parallel-coordinates/pull/265.

These can now by added with a `dimensions` argument in `parcoords`.

### Help Please

@tbadams45, I would appreciate if you could review this.  Let me know if possible.  I had to make some changes in the `js` binding once I updated to the newest `parallel-coordinates.js`.  If anybody else is following along, I'll gladly accept your review also.

### CODE REVIEW

**Comment by tbadams** [comment]
Hi! I think you may have meant to copy different @tbadams, just fyi.

**Comment by timelyportfolio** [comment]
sorry, @tbadams, thanks for letting me know.  needed `45` at the end :)

**Comment by tbadams45** [comment]
@timelyportfolio Yes, I can download and review with my current set-up. I plan to do it today but it might happen a bit later in the week.

**Comment by tbadams45** [comment]
Parcoords without element id seems to be working fine. With the elementID, we still render correctly and are able to do everything we could do before. However, I get the following warning:

```
Warning in `output$adaptation-obj_space`(...) :
  Ignoring explicitly provided widget ID "parcoords-adap"; Shiny doesn't use them
```

I was trying to use brushReset (#28) but wasn't able to - I would presume because of that warning

**Comment by timelyportfolio** [comment]
Ok, this makes sense.  In shiny, the `elementId` is provided in `parcoordsOutput`, so that is the place to give it the `id`. Let me know if this does not make sense.

```
library(parcoords)
library(shiny)

ui <- parcoordsOutput('myparcoordsid')
server <- function(input,output,session){
  output$myparcoordsid <- renderParcoords({
    parcoords(mtcars)
  })
}

shinyApp(ui,server)
```

**Comment by tbadams45** [comment]
Got it. Tested it out and it's working fine. You can close #28 too.

**Comment by tbadams45** [comment]
FWIW, it is strange to me that parcoords() would offer an elementID argument if it will always be explicitly ignored by Shiny.

**Comment by timelyportfolio** [comment]
@tbadams45, thanks for testing.  I'll merge and then start prepping for CRAN.

In terms of `elementId`, `htmlwidgets` operate in multiple contexts.  In the Shiny context, we initialize the output with `parcoordsOutput` without knowledge of what will populate it.  Shiny needs a unique `id` to manage it, so `parcoordsOutput` requires this argument.  The population of the output slot is deferred with a `renderParcoords`.  If the `id` was then overwritten, the Shiny session would not know how to handle and manage.

The `elementId` in `parcoords` is simply a convenience item for non-Shiny contexts, so that a user will know the `id` in advance.  Otherwise, discovery is difficult if we wait for the `htmlwidgets`-randomly assigned `id`.

**Pull request merged**
