### PR TITLE
Added a shiny binding to extract brushed row IDs

### PR DESCRIPTION
**Pull request by albre116**
Hi,
thanks for the great d3.js binding.  We are using it here at the national marrow donor program in a shiny application so I thought I'd share our code changes with you.  Basically, we just added the ability to extract the brushed data in a shiny input$ field.

best
-mark

### CODE REVIEW

**Comment by timelyportfolio** [comment]
Great, this makes me so happy that you are both using and improving.  I glanced quickly through the code.  Can you describe the changes that you made to the d3.parcoords.js?  I generally try to avoid changing the underlying JavaScript library due to ongoing difficulty of maintenance, unless there is an absolute need or we can submit a pull  to the underlying library to incorporate the change.  I look forward to hearing.  I'll go play with it for now and see if I might be able to answer my own question.

Thanks so much again.

**Comment by timelyportfolio** [comment]
@albre116 Never mind, I see now that you just pulled in the latest changes from the parcoords js.  I folllow/watch, but somehow missed this.  I'll play a bit and very likely pull in changes within the hour.

Thanks.

**Comment by albre116** [comment]
Hi,
I did update the underlying javascript libraries because I was hoping that
the paracoord.on("brush",function(d)) call would work  for the 2d-strum
selection, but alas it didn't.

Thx and have a good day

On Thu, Mar 12, 2015 at 2:59 PM, timelyportfolio <notifications@github.com>
wrote:

> @albre116 <https://github.com/albre116> Never mind, I see now that you
> just pulled in the latest changes from the parcoords js. I folllow/watch,
> but somehow missed this. I'll play a bit and very likely pull in changes
> within the hour.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timelyportfolio/parcoords/pull/5#issuecomment-78592857>
> .
>



-- 
Mark Albrecht
albre116@gmail.com
952-261-9903

**Comment by bbroeksema** [comment]
@albre116 What's exactly the issue with on("brush".. )? Is it not fired for strums? I can have a look at it if you give me a bit more details  on what you are expecting. If I understand correctly, you're looking for an update emit on each brush change and iirc there's only on("brushend"...) for strums atm.

**Comment by albre116** [comment]
Ideally, one would use:

parcoords.on("brush", function() {
             var ids = [];
             var selected = this.brushed();
             for (var i = 0; i < selected.length; i++){
               ids.push(selected[i].names);
               }
               //return the brushed row names
               Shiny.onInputChange(el.id + "_brushed_row_names", ids);
           });


However, the "brush" update function is only called for 1D-Selection mode
and won't work for 2D-Strums...   I had to use "render' instead to get the
function to activate.

I don't think there is much to be done unfortunately :)

On Thu, Mar 12, 2015 at 3:21 PM, Bertjan Broeksema <notifications@github.com
> wrote:

> @albre116 <https://github.com/albre116> What's exactly the issue with
> on("brush".. )? Is it not fired for strums? I can have a look at it if you
> give me a bit more details on what you are expecting. If I understand
> correctly, you're looking for an update emit on each brush change and iirc
> there's only on("brushend"...) for strums atm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timelyportfolio/parcoords/pull/5#issuecomment-78599863>
> .
>



-- 
Mark Albrecht
albre116@gmail.com
952-261-9903

**Comment by timelyportfolio** [comment]
@albre, what OS are you working with?  I'm having the same trouble expressed by @markriseley in https://github.com/timelyportfolio/parcoords/pull/4 .  The `colorScale` is not being passed correctly as `JS_EVAL`, so the function is as string.  Just wondering if it is an OS problem.

**Comment by albre116** [comment]
Windows 7

**Comment by timelyportfolio** [comment]
@albre116 would you mind copy/paste `sessionInfo()`?

**Comment by albre116** [comment]
I can later tonight

**Comment by timelyportfolio** [comment]
Also, @albre116 I think we'll need some other indicator besides just a check on shiny mode to make this work.  For example, if we have a static `parcoords` in `UI`, we will get an error.  Or instead of a parameter, we could possibly check for the existence of a `Shiny.onInputChange` function before attempting to run.

**Comment by timelyportfolio** [comment]
@albre116, why do you hide [here](https://github.com/albre116/parcoords/blob/9d2126d4086a76eaf9b320c036303e31a232f1d5/inst/htmlwidgets/parcoords.js#L36-L38)?  I think I would rather only hide when `rownames = F`, and then always provide `rownames` as `names` in the data ignoring `rownames`.

**Comment by albre116** [comment]
Good idea

**Comment by timelyportfolio** [comment]
I'll accept this pull and then make the changes in a subsequent pull.  Thanks again for this.  Still a lot of other improvements, so feel free to let me know if you have any ideas.

**Comment by timelyportfolio** [comment]
@albre116 could you test this from `devtools::install_github("timelyportfolio/parcoords")?

**Comment by albre116** [comment]
Great,
We really are glad you put this code out there to get us up and going on
parcoords.  Thx again

**Pull request merged**
